#!/usr/bin/env -S deno run -A

interface SDKConfig {
  version: string;
  datastarKey: string;
  defaults: {
    booleans: Record<string, boolean>;
    durations: Record<string, number>;
  };
  datalineLiterals: string[];
  enums: {
    [key: string]: {
      description: string;
      default?: string;
      values: Array<{ value: string; description: string; name?: string }>;
    };
  };
}

// Naming convention utilities
const toPascalCase = (str: string): string => 
  str.replace(/(?:^|[\s_-])(\w)/g, (_, char) => char.toUpperCase());

const toCamelCase = (str: string): string => {
  const pascal = toPascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
};

const toConstantCase = (str: string): string =>
  str.replace(/([a-z])([A-Z])/g, '$1_$2').toUpperCase();

// Template for consts.ts
const generateConstsTemplate = (config: SDKConfig): string => {
  const doNotEdit = "This is auto-generated by Datastar. DO NOT EDIT.";
  
  // Generate default durations
  const defaultDurations = Object.entries(config.defaults.durations)
    .map(([key, value]) => {
      const name = toPascalCase(key);
      const description = key === 'sseRetryDuration' 
        ? 'The default duration for retrying SSE on connection reset. This is part of the underlying retry mechanism of SSE.'
        : `Default ${key} duration`;
      
      return `// ${description}
export const Default${name}Ms = ${value};`;
    }).join('\n\n');

  // Generate default booleans  
  const defaultBooleans = Object.entries(config.defaults.booleans)
    .map(([key, value]) => {
      const name = toPascalCase(key);
      const description = key === 'elementsUseViewTransitions'
        ? 'Should elements be patched using the ViewTransition API?'
        : key === 'patchSignalsOnlyIfMissing'
        ? 'Should a given set of signals patch if they are missing?'
        : `Default ${key} setting`;
      
      return `// ${description}
export const Default${name} = ${value};`;
    }).join('\n\n');

  // Generate dataline literals
  const datalineLiterals = config.datalineLiterals
    .map(literal => {
      // Special case for "mode" -> "PatchMode" to match existing usage
      const constName = literal === 'mode' ? 'DatastarDatalinePatchMode' : `DatastarDataline${toPascalCase(literal)}`;
      return `export const ${constName} = "${toCamelCase(literal)}"`;
    })
    .join('\n');

  // Generate enums
  const enums = Object.entries(config.enums)
    .map(([enumName, enumDef]) => {
      const values = enumDef.values
        .map(entry => `// ${entry.description}\n    "${entry.value}",`)
        .join('\n');
      
      const defaultValue = enumDef.default 
        ? `\n// Default value for ${enumName}\nexport const Default${enumName} = "${enumDef.default}";`
        : '';

      return `// ${enumDef.description}
export const ${enumName}s = [
${values}
] as const;${defaultValue}`;
    }).join('\n\n');

  return `// ${doNotEdit}

export const DATASTAR = "${config.datastarKey}" as const;
export const DATASTAR_REQUEST = "${toPascalCase(config.datastarKey)}-Request";
export const VERSION = "${config.version}";

// #region Defaults

// #region Default durations

${defaultDurations}

// #endregion


// #region Default booleans

${defaultBooleans}

// #endregion

// #region Datalines

${datalineLiterals}
// #endregion


// #region Enums

${enums}
// #endregion

// #endregion
`;
};

// Template for types.ts
const generateTypesTemplate = (config: SDKConfig): string => {
  // Generate imports based on what we actually have
  const datalineImports = config.datalineLiterals
    .map(literal => {
      const constName = literal === 'mode' ? 'DatastarDatalinePatchMode' : `DatastarDataline${toPascalCase(literal)}`;
      return `  ${constName},`;
    })
    .join('\n');
  
  const defaultImports = [
    `  DefaultElementPatchMode,`,
    ...Object.keys(config.defaults.booleans).map(key => `  Default${toPascalCase(key)},`),
    ...Object.keys(config.enums).map(name => `  Default${name},`).filter(imp => 
      config.enums[name.replace('Default', '')]?.default
    )
  ].join('\n');
  
  const enumImports = Object.keys(config.enums)
    .map(name => `  ${name}s,`)
    .join('\n');

  // Generate interface properties dynamically
  const elementOptionsProps = config.datalineLiterals
    .filter(literal => literal.includes('useViewTransition'))
    .map(literal => `  [DatastarDataline${toPascalCase(literal)}]?: boolean;`)
    .join('\n');

  const patchElementsProps = config.datalineLiterals
    .filter(literal => ['mode', 'selector'].some(prop => literal.includes(prop)))
    .map(literal => {
      if (literal.includes('mode')) {
        return `  [DatastarDatalinePatchMode]?: ElementPatchMode;`;
      }
      if (literal.includes('selector')) {
        return `  [DatastarDataline${toPascalCase(literal)}]?: string;`;
      }
      return '';
    })
    .filter(prop => prop)
    .join('\n');

  const patchSignalsProps = config.datalineLiterals
    .filter(literal => literal.includes('onlyIfMissing'))
    .map(literal => `  [DatastarDataline${toPascalCase(literal)}]?: boolean;`)
    .join('\n');

  // Generate event interfaces dynamically
  const eventInterfaces = Object.entries(config.enums.EventType?.values || [])
    .map(([_, event]) => {
      const eventName = event.name || toPascalCase(event.value.replace('datastar-', ''));
      const datalineKey = event.value.includes('elements') ? 'Elements' : 'Signals';
      const optionsType = event.value.includes('elements') ? 'PatchElementsOptions' : 'PatchSignalsOptions';
      const dataType = event.value.includes('elements') ? 'string' : 'Record<string, Jsonifiable>';
      
      return `export interface ${toCamelCase(eventName)}Event {
  event: "${event.value}";
  options: ${optionsType};
  [DatastarDataline${datalineKey}]: ${dataType};
}`;
    }).join('\n\n');

  // Generate default mapping dynamically
  const defaultMappings = [
    // Add patch mode mapping
    `  [DatastarDatalinePatchMode]: DefaultElementPatchMode,`,
    // Map each boolean default to its corresponding dataline literal
    ...Object.keys(config.defaults.booleans)
      .map(key => {
        if (key === 'elementsUseViewTransitions') {
          return `  [DatastarDatalineUseViewTransition]: DefaultElementsUseViewTransitions,`;
        } else if (key === 'patchSignalsOnlyIfMissing') {
          return `  [DatastarDatalineOnlyIfMissing]: DefaultPatchSignalsOnlyIfMissing,`;
        }
        return '';
      })
      .filter(mapping => mapping)
  ].join('\n');

  return `import {
${datalineImports}
${defaultImports}
${enumImports}
} from "./consts.ts";

// Simple Jsonifiable type definition to replace npm:type-fest dependency
export type Jsonifiable = 
  | string 
  | number 
  | boolean 
  | null 
  | undefined
  | Jsonifiable[] 
  | { [key: string]: Jsonifiable };

export type ElementPatchMode = typeof ElementPatchModes[number];
export type EventType = typeof EventTypes[number];

export type StreamOptions = Partial<{
  onError: (error: unknown) => Promise<void> | void;
  onAbort: (reason?: string) => Promise<void> | void;
  responseInit: Record<string, unknown>;
  keepalive: boolean;
}>

export interface DatastarEventOptions {
  eventId?: string;
  retryDuration?: number;
}

export interface ElementOptions extends DatastarEventOptions {
${elementOptionsProps}
}

export interface PatchElementsOptions extends ElementOptions {
${patchElementsProps}
}

${eventInterfaces}

export interface PatchSignalsOptions extends DatastarEventOptions {
${patchSignalsProps}
}

export const sseHeaders = {
  "Cache-Control": "no-cache",
  "Connection": "keep-alive",
  "Content-Type": "text/event-stream",
} as const;

export type MultilineDatalinePrefix =
  | typeof DatastarDatalineElements
  | typeof DatastarDatalineSignals;

export type DatastarEventOptionsUnion =
  | PatchElementsOptions
  | ElementOptions
  | PatchSignalsOptions
  | DatastarEventOptions;

export type DatastarEvent =
  | patchElementsEvent
  | patchSignalsEvent;

export const DefaultMapping = {
${defaultMappings}
} as const;

`;
};

async function main() {
  try {
    // Read the configuration file
    const configPath = "./datastar-sdk-config-v1.json";
    const configText = await Deno.readTextFile(configPath);
    const config: SDKConfig = JSON.parse(configText);
    
    // Generate consts.ts
    const constsContent = generateConstsTemplate(config);
    await Deno.writeTextFile("./src/consts.ts", constsContent);
    console.log("✅ Generated src/consts.ts");
    
    // Generate types.ts
    const typesContent = generateTypesTemplate(config);
    await Deno.writeTextFile("./src/types.ts", typesContent);
    console.log("✅ Generated src/types.ts");
    
    console.log("🎉 Code generation complete!");
    
  } catch (error) {
    console.error("❌ Error generating code:", error);
    Deno.exit(1);
  }
}

if (import.meta.main) {
  await main();
} 