// This is auto-generated by Datastar. DO NOT EDIT.

export const DATASTAR = "datastar" as const;
export const DATASTAR_REQUEST = "Datastar-Request";
export const VERSION = "1.0.0-RC.1";

// #region Defaults

// #region Default durations

// The default duration for retrying SSE on connection reset. This is part of the underlying retry mechanism of SSE.
export const DefaultSseRetryDurationMs = 1000;

// #endregion


// #region Default booleans

// Should elements be patched using the ViewTransition API?
export const DefaultElementsUseViewTransitions = false;

// Should a given set of signals patch if they are missing?
export const DefaultPatchSignalsOnlyIfMissing = false;

// #endregion

// #region Datalines

export const DatastarDatalineSelector = "selector"
export const DatastarDatalinePatchMode = "mode"
export const DatastarDatalineElements = "elements"
export const DatastarDatalineUseViewTransition = "useViewTransition"
export const DatastarDatalineSignals = "signals"
export const DatastarDatalineOnlyIfMissing = "onlyIfMissing"
// #endregion


// #region Enums

// The mode in which an element is patched into the DOM.
export const ElementPatchModes = [
// Morphs the element into the existing element.
    "outer",
// Replaces the inner HTML of the existing element.
    "inner",
// Removes the existing element.
    "remove",
// Replaces the existing element with the new element.
    "replace",
// Prepends the element inside to the existing element.
    "prepend",
// Appends the element inside the existing element.
    "append",
// Inserts the element before the existing element.
    "before",
// Inserts the element after the existing element.
    "after",
] as const;
// Default value for ElementPatchMode
export const DefaultElementPatchMode = "outer";

// The type protocol on top of SSE which allows for core pushed based communication between the server and the client.
export const EventTypes = [
// An event for patching HTML elements into the DOM.
    "datastar-patch-elements",
// An event for patching signals.
    "datastar-patch-signals",
] as const;
// #endregion

// #endregion
